//
// Created by Joseph Azrak on 16/08/2020.
//

#ifndef CPP_SATELLITE_ANALYZER_PROJECT_SETTINGS_H
#define CPP_SATELLITE_ANALYZER_PROJECT_SETTINGS_H

const int    PRINTOFF_ROUND_SF = 5;
const int    TABLE_OUTPUT_PADDING = 13;
const double GRAVITATIONAL_CONSTANT = 6.67e-11;
const double RADIUS_OF_THE_EARTH = 6371 * pow(10, 3);
const int    DISQ_REASON_MISSING_PARAMETER = -1;
const int    DISQ_REASON_ECCENTRICITY = -2;
const double LITERATURE_VALUE = 5.97e24;

#endif //CPP_SATELLITE_ANALYZER_PROJECT_SETTINGS_H
